### ISSUE TITLE
[Bug] wireless grid NBT does not update when in curio slot

### ISSUE THREAD

**Issue by AlienXtream** [starforcraft/Refined-Curios#1]
the NBT data for things like crafting table contents and settings do not update while in curio's slot. this causes both deletion and duplication of items in said crafting grid (depending on if the grid was populated from hotbar/inventory or curio slot). this is... bad. please fix asap

**Comment by starforcraft** [comment]
Will fix after vacation :)

**Comment by starforcraft** [comment]
Refined implemented the support now themself
